version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongo_db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/db/mongodb/database:/data/db
    ports:
      - 27017:27017
