version: "3.8"
services:

  mysql:
    image: mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/db/mysql:/var/lib/mysql
