version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - /home/db/postgres:/var/lib/postgresql/data
